# Dockerfile_arm64v8

FROM arm64v8/ubuntu:20.04

ENV DEBFULLNAME Chugunov Roman
ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV HOME /root
ENV PATH /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/root/.cargo/bin:/usr/src/figma-linux/.node_modules/.bin

WORKDIR /usr/src/figma-linux

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    apt install -y --no-install-recommends \
    apt-utils \
    devscripts \
    libfreetype6 \
    dput \
    build-essential \
    lsb-release \
    equivs \
    git \
    curl \
    git-buildpackage \
    nano \
    npm \
    rpm \
    libfuse2 \
    python \
    ruby \
    ruby-dev \
    libarchive-tools \
    pristine-tar && \
    gem install fpm -v 1.10.2 && \
    curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt install -y --no-install-recommends nodejs && \
    cd /tmp && \
    apt-get download fuse && \
    dpkg-deb -x fuse_* . && \
    dpkg-deb -e fuse_* && \
    rm fuse_*.deb && \
    echo -en '#!/bin/bash\nexit 0\n' > DEBIAN/postinst && \
    dpkg-deb -b . /fuse.deb && \
    dpkg -i /fuse.deb && \
    cd /usr/src/figma-linux && \
    curl -L https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-aarch64.AppImage --output ./appimagetool-aarch64.AppImage && \
    ln -s /usr/lib/aarch64-linux-gnu/libfreetype.so.6 /usr/lib/libfreetype.so.6 && \
    ln -s /usr/lib/aarch64-linux-gnu/libfreetype.so.6 /usr/lib/libfreetype.so && \
    ldconfig && \
    mv ./appimagetool-aarch64.AppImage /bin/appimagetool && \
    chmod +x /bin/appimagetool && \
    mkdir -p /root/.cargo/bin && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives