FROM ubuntu:20.04

ENV DEBFULLNAME Chugunov Roman
ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV HOME /root

WORKDIR /usr/src/figma-linux

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    apt install -y --no-install-recommends \
    devscripts \
    dput \
    build-essential \
    git \
    curl \
    debhelper \
    rsync \
    ssh \
    python3-paramiko && \
    mkdir -p ~/.ssh && \
    chmod 700 ~/.ssh && \
    touch ~/.ssh/known_hosts && \
    ssh-keyscan ppa.launchpad.net >> ~/.ssh/known_hosts && \
    echo "[ppa-figma]" >> /root/.dput.cf && \
    echo "fqdn = ppa.launchpad.net" >> /root/.dput.cf && \
    echo "method = sftp" >> /root/.dput.cf && \
    echo "incoming = ~chrdevs/ubuntu/figma" >> /root/.dput.cf && \
    echo "login = chrdevs" >> /root/.dput.cf && \
    echo "allow_unsigned_uploads = 1" >> /root/.dput.cf && \
    echo "ssh_config_options = IdentityFile ~/.ssh/id_rsa" >> /root/.dput.cf && \
    echo "DEBSIGN_MAINT='Chugunov Roman'" >> /etc/devscripts.conf