name: Build

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        id: checkout
        uses: actions/checkout@v2

      - name: Cache src
        id: cache-src
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./*

  build_arm64v8:
    needs: setup
    name: build for arm64v8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: src
          path: ./

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_arm64v8
          push: true
          tags: 4tqrgqe5yrgfd/figma-linux-docker-image-arm:latest

  build_amd64:
    runs-on: ubuntu-latest
    name: build for amd64
    needs: setup
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: src
          path: ./

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_amd64
          push: true
          tags: 4tqrgqe5yrgfd/figma-linux-docker-image:latest

  build_ppa:
    runs-on: ubuntu-latest
    name: build PPA
    needs: setup
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: src
          path: ./

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_ppa
          push: true
          tags: 4tqrgqe5yrgfd/figma-linux-docker-image-ppa:latest
